Ohm 689 measure performance
jembi/openhim-performance pull request #2
Opened 2019-02-13 06:42 UTC by bradsawadye

2019-02-14 11:28 UTC, Zooloo2014 requested changes
My biggest concern is the duplication in the module:
- can constant values that are duplicated by replaced with variables and/or passed in as parameters?
- can the create droplet, create of host file and writing of the ip address be pulled into its' own role, and called in a loop to create each instance?

@bausmeier Your thoughts? I'm not sure how generic we want to make this

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    size_id: 512mb
Can this be parameterised as a variable?
So that if it needs to to be changed, it can be done in one place, e,g. vars/main.yml or an environment variable

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    image_id: ubuntu-18-04-x64
https://github.com/jembi/openhim-performance/blob/594884266aaad5d336a5992be981bcbb98182747/roles/common/tasks/main.yml#L21-L22

Can these also parameterised ?
For future tests, we may want to use a different image (e.g. 16.10, 19.10) or run in a different region.

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +        image_id: ubuntu-18-04-x64
https://github.com/jembi/openhim-performance/blob/594884266aaad5d336a5992be981bcbb98182747/roles/common/tasks/main.yml#L33-L36

Can these also parameterised ?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +        image_id: ubuntu-18-04-x64
https://github.com/jembi/openhim-performance/blob/594884266aaad5d336a5992be981bcbb98182747/roles/common/tasks/main.yml#L59-L62

Can these also parameterised ?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +        image_id: ubuntu-18-04-x64
https://github.com/jembi/openhim-performance/blob/594884266aaad5d336a5992be981bcbb98182747/roles/common/tasks/main.yml#L46-L49

Can these also parameterised ?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?
So that it's value is only set in one place

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?

2019-02-14 11:28 UTC, Zooloo2014 commented on roles/common/tasks/main.yml
> +    path: ../inventory/new/hosts
Can this be stored in a variable?

2019-02-14 12:34 UTC, bausmeier commented
@Zooloo2014 I agree. I think it would be good to parameterise the tasks so that the droplet sizes etc. can be configured. The db servers and app servers might need different specs for example. Or we might want to test on different OS versions.

2019-02-18 06:49 UTC, Zooloo2014 commented
Can the install of python and pip be included as part of droplet creation? 
[Install python and pip](https://gist.github.com/Zooloo2014/4b70adc9a1c2396f1f4ef95920e8a077)
Ansible seems to need these in order to run modules on the target machines.
`
TASK [Gathering Facts] ***********************************************************************************************************
fatal: [209.97.151.231]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 209.97.151.231 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
fatal: [142.93.65.232]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 142.93.65.232 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
fatal: [138.197.14.110]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 138.197.14.110 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
`

2019-02-18 08:50 UTC, Zooloo2014 commented
The last changes for this PR: 

* The SSH check in roles/common/tasks.main.yml fails (possibly because of parameter types/values supplied). This [gist](https://gist.github.com/Zooloo2014/29c7552b31f5069669caae7b5d1d2f82) works with your script
* The installation of python needs to be run against the hosts file that is generated by the create-servers.yml playbook, and so cannot be run in this playbook which targets `localhost`. We'll need to extract the initial server setup into its' own playbook. Please remove the changes for [3d0910f](/jembi/openhim-performance/pull/2/commits/3d0910f77a0ef145b9ad7db08be6cf09c1e24ece) from this PR. I will add an additional playbook as part of [Add script to destroy provisioned servers after performance tests #3](https://github.com/jembi/openhim-performance/pull/3)

2019-02-18 11:45 UTC, Zooloo2014 commented
> The last changes for this PR:
> 
> * The SSH check in roles/common/tasks.main.yml fails (possibly because of parameter types/values supplied). This [gist](https://gist.github.com/Zooloo2014/29c7552b31f5069669caae7b5d1d2f82) works with your script
> * The installation of python needs to be run against the hosts file that is generated by the create-servers.yml playbook, and so cannot be run in this playbook which targets `localhost`. We'll need to extract the initial server setup into its' own playbook. Please remove the changes for [3d0910f](/jembi/openhim-performance/pull/2/commits/3d0910f77a0ef145b9ad7db08be6cf09c1e24ece) from this PR. I will add an additional playbook as part of [Add script to destroy provisioned servers after performance tests #3](https://github.com/jembi/openhim-performance/pull/3)

- SSH keys are pre-populated in DigitalOcean, but will need to have a similarly-name private key in the local .ssh directory

2019-02-18 11:45 UTC, merged